os: linux
compiler: clang
language: cpp
addons:
  apt:
    packages:
    - ninja-build
    - cmake
env:
- LIBWEBRTC_VERSION=1.0.0-faf5
install:
- wget https://github.com/FAForever/libwebrtc/releases/download/v$LIBWEBRTC_VERSION/libwebrtc-$LIBWEBRTC_VERSION-linux-x64.tar.gz
  -O libwebrtc.tar.gz
script:
- tar xf libwebrtc.tar.gz
- mkdir build && cd build
- cmake -G "Ninja"
  -DCMAKE_CXX_COMPILER="/usr/local/clang-5.0.0/bin/clang++"
  -DWEBRTC_INCLUDE_DIRS="$TRAVIS_BUILD_DIR/include"
  -DWEBRTC_LIBRARIES="$TRAVIS_BUILD_DIR/lib/libwebrtc.a"
  -DCMAKE_BUILD_TYPE=Release
  ..
- ninja faf-ice-adapter
- tar -cJvf ../faf-ice-adapter-linux64.tar.xz faf-ice-adapter
deploy:
  provider: releases
  api_key:
    secure: UKcH+VCoVZ+qI/uT2UK8EKe47+ppZTpEj1Gdn4sDJmuHMZjMWAHH9LyNBV/sWyOOcs1ECGuqs0LBpi45mbGIdsCGDd6d8azqO9pEq+s4tX4RQgqFu6MRAkLtt5985TxTRw615arGliRKWUbEbYGtOxkTz0BA4L6TsPHQlUKn4BJjCjPRCWbTPBp0TX3XDx8zwePghwBLX9p1QmMhq7u6LHsWZe61Z6th7fuvY2aZF9qp7OjItNkhzhp/5NaT6icL+v69TKQpOyRgqIjoA4iv24xkiNbtHbI6Q3Y8AnV9TjF3aWreFNTjver1VZVdm3czEcqgI/Ih+KsuCdaUj1KieBG8NjQZygqitHxdwunAk1G/8ZSX9tvTGxlsqbSh8UDj65qgxYMSuDqR8HDBhKBdPe+LjzMu7lvgaciT89cYfg7suiNfXZwP0KBefIZX00YhkGfCHqMJ2sacsikzNL4YC0FsOUrpQ5D4GwswaZljM4VjuvfKfo4zkRhI2FblO/37KsVYEWGhZdWHyy7pk20WjVcX7r9Kyc9/UrZYMA3Sv65JohNsxJs4zYulpe8747/uhYGnPKj4vI+acOiQyIqLdLp6k1o0M2cfhcuhQbPdT0tv4s9ctZcGbezzBAhFbaNdCI5kNcVwopVV3kseIpRN5HA3LEKfV2LTq8ha4wFAg7U=
  file: adsffaf-ice-adapter-linux64.tar.xz
  skip_cleanup: true
  on:
    repo: muellni/ice-adapter
    tags: true
  prerelease: true
